detectors:
  ControlParameter:
    exclude:
      - Anthropic#self.api_key=
  TooManyStatements:
    exclude:
      - 'Anthropic::Client#self.post'
  BooleanParameter:
    exclude:
      - 'Anthropic::Messages#initialize'
  DuplicateMethodCall:
    exclude:
      - 'Anthropic::Messages#create'
