detectors:
  ControlParameter:
    exclude:
      - Anthropic#self.api_key=
  TooManyStatements:
    exclude:
      - 'Anthropic::Api::Concerns::Validatable#schema'
      - 'Anthropic::BaseApi#beta_config'
      - 'Anthropic::BaseApi#version_config'
      - 'Anthropic::Bootstrapper#self.load_betas'
      - 'Anthropic::Bootstrapper#self.load_versions'
      - 'Anthropic::Client::Standard#self.post'
      - 'Anthropic::Client::Streaming#self.post'
  BooleanParameter:
    exclude:
      - 'Anthropic::Messages#initialize'
  DuplicateMethodCall:
    exclude:
      - 'Anthropic::BaseApi#version_config'
      - 'Anthropic::Messages#create'
  InstanceVariableAssumption:
    exclude:
      - 'Anthropic::BaseApi'
  NestedIterators:
    exclude:
      - 'Anthropic::Bootstrapper#self.load_versions'
