detectors:
  ControlParameter:
    exclude:
      - Anthropic#self.api_key=
  TooManyStatements:
    exclude:
      - 'Anthropic::Api::Concerns::Validatable#schema'
      - 'Anthropic::Api::Base#beta_config'
      - 'Anthropic::Api::Base#version_config'
      - 'Anthropic::Bootstrapper#self.load_betas'
      - 'Anthropic::Bootstrapper#self.load_versions'
      - 'Anthropic::Client::Standard#self.post'
      - 'Anthropic::Client::Streaming#self.post'
  DuplicateMethodCall:
    exclude:
      - 'Anthropic::Api::Base#version_config'
  InstanceVariableAssumption:
    exclude:
      - 'Anthropic::Api::Base'
  NestedIterators:
    exclude:
      - 'Anthropic::Bootstrapper#self.load_versions'
