require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
Naming/RescuedExceptionsVariableName:
  Enabled: false
Layout/LineLength:
  Max: 120
