name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop

  reek:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run reek
      run: bundle exec reek

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.3', '3.2.4']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Specs
      run: bundle exec rspec
